# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cd55a0a9c56bd3986c2504f043681fe1db4dc3eb9b8e25ff28389eafcaf30f9fa73328dd641146f9a25335e4c910378f1d9ac39c75e9040426d104064a65a9bd

test:
  secret_key_base: 19563b015dda5a800b61734f5a6cb5256cb275b53a8a37b564ddbc681758bee26b7724e3008ebec65b29e3a01444110749663c4ec7ffc012ad0ca7bb1e67b1bc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
